In [1]:
import pandas as pd

df = pd.read_csv("../data/SampleSuperstore.csv")

In [3]:
df.shape

(9994, 13)

In [4]:
df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

In [16]:
df.columns

Index(['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Category', 'Sub-Category', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ship Mode     9994 non-null   str
 1   Segment       9994 non-null   str
 2   Country       9994 non-null   str
 3   City          9994 non-null   str
 4   State         9994 non-null   str
 5   Postal Code   9994 non-null   int64
 6   Region        9994 non-null   str
 7   Category      9994 non-null   str
 8   Sub-Category  9994 non-null   str
 9   Sales         9994 non-null   float64
 10  Quantity      9994 non-null   int64
 11  Discount      9994 non-null   float64
 12  Profit        9994 non-null   float64
dtypes: float64(3), int64(2), str(8)
memory usage: 1015.1 KB

In [6]:
df.describe()

        Postal Code         Sales     Quantity     Discount       Profit
count   9994.000000   9994.000000  9994.000000  9994.000000  9994.000000
mean   55190.379428    229.858001     3.789574     0.156203    28.656896
std    32063.693350    623.245101     2.225110     0.206452   234.260108
min     1040.000000      0.444000     1.000000     0.000000 -6599.978000
25%    23223.000000     17.280000     2.000000     0.000000     1.728750
50%    56430.500000     54.490000     3.000000     0.200000     8.666500
75%    90008.000000    209.940000     5.000000     0.200000    29.364000
max    99301.000000  22638.480000    14.000000     0.800000  8399.976000

In [7]:
df.nunique()

Ship Mode          4
Segment            3
Country            1
City             531
State             49
Postal Code      631
Region             4
Category           3
Sub-Category      17
Sales           5825
Quantity          14
Discount          12
Profit          7287
dtype: int64

In [11]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Ship Mode,9994,4,Standard Class,5968,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Segment,9994,3,Consumer,5191,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country,9994,1,United States,9994,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,9994,531,New York City,915,NaN,NaN,NaN,NaN,NaN,NaN,NaN
State,9994,49,California,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Postal Code,9994.0,NaN,NaN,NaN,55190.379428,32063.69335,1040.0,23223.0,56430.5,90008.0,99301.0
Region,9994,4,West,3203,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,9994,3,Office Supplies,6026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sub-Category,9994,17,Binders,1523,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sales,9994.0,NaN,NaN,NaN,229.858001,623.245101,0.444,17.28,54.49,209.94,22638.48
Quantity,9994.0,NaN,NaN,NaN,3.789574,2.22511,1.0,2.0,3.0,5.0,14.0
Discount,9994.0,NaN,NaN,NaN,0.156203,0.206452,0.0,0.0,0.2,0.2,0.8
Profit,9994.0,NaN,NaN,NaN,28.656896,234.260108,-6599.978,1.72875,8.6665,29.364,8399.976

In [12]:
df.nunique().sort_values()

Country            1
Segment            3
Category           3
Ship Mode          4
Region             4
Discount          12
Quantity          14
Sub-Category      17
State             49
City             531
Postal Code      631
Sales           5825
Profit          7287
dtype: int64

In [14]:
df['Discount'].value_counts().sort_index()

Discount
0.00    4798
0.10      94
0.15      52
0.20    3657
0.30     227
0.32      27
0.40     206
0.45      11
0.50      66
0.60     138
0.70     418
0.80     300
Name: count, dtype: int64

In [15]:
 df.groupby("Discount")["Profit"].agg(["count", "mean", "sum"])

          count        mean          sum
Discount
0.00       4798   66.900292  320987.6032
0.10         94   96.055074    9029.1770
0.15         52   27.288298    1418.9915
0.20       3657   24.702572   90337.3060
0.30        227  -45.679636  -10369.2774
0.32         27  -88.560656   -2391.1377
0.40        206 -111.927429  -23057.0504
0.45         11 -226.646464   -2493.1111
0.50         66 -310.703456  -20506.4281
0.60        138  -43.077212   -5944.6552
0.70        418  -95.874060  -40075.3569
0.80        300 -101.796797  -30539.0392

In [17]:
df.groupby("Region")[["Sales", "Profit"]].sum().sort_values("Profit", ascending=False)

               Sales       Profit
Region
West     725457.8245  108418.4489
East     678781.2400   91522.7800
South    391721.9050   46749.4303
Central  501239.8908   39706.3625

In [18]:
df.groupby("Region").agg(
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum"),
    Quantity=("Quantity", "sum")
).sort_values("Profit", ascending=False)

               Sales       Profit  Quantity
Region
West     725457.8245  108418.4489     12266
East     678781.2400   91522.7800     10618
South    391721.9050   46749.4303      6209
Central  501239.8908   39706.3625      8780

In [19]:
df.groupby("Region").agg(
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum")
).assign(
    Profit_Margin=lambda x: x["Profit"] / x["Sales"]
).sort_values("Profit_Margin", ascending=False)

               Sales       Profit  Profit_Margin
Region
West     725457.8245  108418.4489       0.149448
East     678781.2400   91522.7800       0.134834
South    391721.9050   46749.4303       0.119343
Central  501239.8908   39706.3625       0.079216