In [1]:
import pandas as pd

df = pd.read_csv("../data/SampleSuperstore.csv")

In [31]:
df.duplicated().sum()

np.int64(17)

In [32]:
df[df.duplicated(keep=False)].sort_values(list(df.columns)).head(20)

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
6409,First Class,Consumer,United States,Houston,Texas,77041,Central,Office Supplies,Paper,47.952,3,0.2,16.1838
8032,First Class,Consumer,United States,Houston,Texas,77041,Central,Office Supplies,Paper,47.952,3,0.2,16.1838
5493,Same Day,Home Office,United States,San Francisco,California,94122,West,Office Supplies,Labels,41.400,4,0.0,19.8720
5905,Same Day,Home Office,United States,San Francisco,California,94122,West,Office Supplies,Labels,41.400,4,0.0,19.8720
2807,Second Class,Consumer,United States,Seattle,Washington,98115,West,Office Supplies,Paper,12.960,2,0.0,6.2208
8095,Second Class,Consumer,United States,Seattle,Washington,98115,West,Office Supplies,Paper,12.960,2,0.0,6.2208
8457,Second Class,Corporate,United States,Chicago,Illinois,60653,Central,Office Supplies,Binders,3.564,3,0.8,-6.2370
9477,Second Class,Corporate,United States,Chicago,Illinois,60653,Central,Office Supplies,Binders,3.564,3,0.8,-6.2370
8533,Standard Class,Consumer,United States,Detroit,Michigan,48227,Central,Furniture,Chairs,389.970,3,0.0,35.0973
9262,Standard Class,Consumer,United States,Detroit,Michigan,48227,Central,Furniture,Chairs,389.970,3,0.0,35.0973
2836,Standard Class,Consumer,United States,Los Angeles,California,90036,West,Office Supplies,Paper,19.440,3,0.0,9.3312
4117,Standard Class,Consumer,United States,Los Angeles,California,90036,West,Office Supplies,Paper,19.440,3,0.0,9.3312
3127,Standard Class,Consumer,United States,New York City,New York,10011,East,Office Supplies,Paper,49.120,4,0.0,23.0864
6334,Standard Class,Consumer,United States,New York City,New York,10011,East,Office Supplies,Paper,49.120,4,0.0,23.0864
591,Standard Class,Consumer,United States,Salem,Oregon,97301,West,Office Supplies,Paper,10.368,2,0.2,3.6288
3670,Standard Class,Consumer,United States,Salem,Oregon,97301,West,Office Supplies,Paper,10.368,2,0.2,3.6288
2803,Standard Class,Consumer,United States,San Francisco,California,94122,West,Office Supplies,Paper,12.840,3,0.0,5.7780
4553,Standard Class,Consumer,United States,San Francisco,California,94122,West,Office Supplies,Paper,12.840,3,0.0,5.7780
1479,Standard Class,Consumer,United States,San Francisco,California,94122,West,Office Supplies,Paper,25.920,4,0.0,12.4416
7608,Standard Class,Consumer,United States,San Francisco,California,94122,West,Office Supplies,Paper,25.920,4,0.0,12.4416

In [41]:
df = df.drop_duplicates()

In [42]:
df.duplicated().sum()

np.int64(0)

In [39]:
data = {
    "Product": ["Apple", "Banana", "Cherry","Cherry","Cherry","Banana"],
    "Price": [0.50, 0.30, 0.85,0.85,0.85,0.30],
    "Stock": [150, 200, 95,95,95,200]
}

df2 = pd.DataFrame(data)

In [40]:
df2[df2.duplicated(keep=False)].sort_values(list(df2.columns)).head()

  Product  Price  Stock
1  Banana   0.30    200
5  Banana   0.30    200
2  Cherry   0.85     95
3  Cherry   0.85     95
4  Cherry   0.85     95

In [43]:
for col in ["Ship Mode","Segment","Country","Region","Category","Sub-Category"]:
    print(col, df[col].unique())

Ship Mode <StringArray>
['Second Class', 'Standard Class', 'First Class', 'Same Day']
Length: 4, dtype: str
Segment <StringArray>
['Consumer', 'Corporate', 'Home Office']
Length: 3, dtype: str
Country <StringArray>
['United States']
Length: 1, dtype: str
Region <StringArray>
['South', 'West', 'Central', 'East']
Length: 4, dtype: str
Category <StringArray>
['Furniture', 'Office Supplies', 'Technology']
Length: 3, dtype: str
Sub-Category <StringArray>
[  'Bookcases',      'Chairs',      'Labels',      'Tables',     'Storage',
 'Furnishings',         'Art',      'Phones',     'Binders',  'Appliances',
       'Paper', 'Accessories',   'Envelopes',   'Fasteners',    'Supplies',
    'Machines',     'Copiers']
Length: 17, dtype: str

In [44]:
df[["Sales", "Quantity", "Discount", "Profit"]].describe()

              Sales     Quantity     Discount      Profit
count   9977.000000  9977.000000  9977.000000  9977.00000
mean     230.148902     3.790719     0.156278    28.69013
std      623.721409     2.226657     0.206455   234.45784
min        0.444000     1.000000     0.000000 -6599.97800
25%       17.300000     2.000000     0.000000     1.72620
50%       54.816000     3.000000     0.200000     8.67100
75%      209.970000     5.000000     0.200000    29.37200
max    22638.480000    14.000000     0.800000  8399.97600

In [45]:
df.to_csv("../data/superstore_clean.csv", index=False)