In [3]:
import warnings
warnings.filterwarnings("ignore")

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)
pd.set_option("display.float_format", lambda x: f"{x:,.3f}")

sns.set_theme(style="whitegrid")

In [7]:
FILE_PATH = "StudentsPerformance.csv"

df = pd.read_csv(FILE_PATH)

original_df = df.copy(deep = True)
analysis_df = df.copy(deep = True)

print(f"Dataset loaded successfully: {FILE_PATH}")
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]:,}")

Dataset loaded successfully: StudentsPerformance.csv
Rows: 1,000
Columns: 8

In [9]:
display(df.head())
display(df.tail())

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [11]:
print("Shape:", df.shape)
print("Column names:")

for i, col in enumerate(df.columns, start = 1):
    print(f"{i}. {col}")

Shape: (1000, 8)
Column names:
1. gender
2. race/ethnicity
3. parental level of education
4. lunch
5. test preparation course
6. math score
7. reading score
8. writing score

In [22]:
print("\nData types:")
display(df.dtypes.rename("dtype").to_frame())

print("\nDataFrame info:")
df.info()

print("\nDescriptive summary:")
display(df.describe(include="all").T)

Data types:

                             dtype
gender                         str
race/ethnicity                 str
parental level of education    str
lunch                          str
test preparation course        str
math score                   int64
reading score                int64
writing score                int64

DataFrame info:
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

Descriptive summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
gender,1000,2,female,518,NaN,NaN,NaN,NaN,NaN,NaN,NaN
race/ethnicity,1000,5,group C,319,NaN,NaN,NaN,NaN,NaN,NaN,NaN
parental level of education,1000,6,some college,226,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lunch,1000,2,standard,645,NaN,NaN,NaN,NaN,NaN,NaN,NaN
test preparation course,1000,2,none,642,NaN,NaN,NaN,NaN,NaN,NaN,NaN
math score,"1,000.000",NaN,NaN,NaN,66.089,15.163,0.000,57.000,66.000,77.000,100.000
reading score,"1,000.000",NaN,NaN,NaN,69.169,14.600,17.000,59.000,70.000,79.000,100.000
writing score,"1,000.000",NaN,NaN,NaN,68.054,15.196,10.000,57.750,69.000,79.000,100.000

In [31]:
numerical_columns = df.select_dtypes(include=np.number).columns.tolist()
categorical_columns = df.select_dtypes(include = ["object","category","bool"]).columns.tolist()

print("Numerical columns:", numerical_columns)
print("Categorical columns:", categorical_columns)

print("\nNumber of numerical columns:", len(numerical_columns))
print("Number of categorical columns:", len(categorical_columns))

Numerical columns: ['math score', 'reading score', 'writing score']
Categorical columns: ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course']

Number of numerical columns: 3
Number of categorical columns: 5